-- DROP TABLE IF EXISTS `address_types`;
-- CREATE TABLE `Categories` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name_en` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `name_zh` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   `deleted_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;